#!/bin/bash
#
# bahmni-two-factor-auth      start/stop/status/debug/restart script
#
# chkconfig: - 64 36
# processname: bahmni-two-factor-auth
# config: /etc/default/bahmni-two-factor-auth
# pidfile: /var/run/bahmni-two-factor-auth/bahmni-two-factor-auth.pid

export BAHMNI_TWO_FACTOR_AUTH_USER=bahmni
export BAHMNI_TWO_FACTOR_AUTH_RUN=/opt/bahmni-two-factor-auth/bin/start.sh
export BAHMNI_TWO_FACTOR_AUTH_DEBUG=/opt/bahmni-two-factor-auth/bin/debug.sh
export CUR_USER=`/usr/bin/whoami`

. /etc/bahmni-two-factor-auth/bahmni-two-factor-auth.conf

create_dirs() {
    if [[ ! -e /var/run/bahmni-two-factor-auth ]]; then
        ln -s /opt/bahmni-two-factor-auth/run /var/run/bahmni-two-factor-auth
    fi

    if [[ ! -e /var/log/bahmni-two-factor-auth ]]; then
        ln -s /opt/bahmni-two-factor-auth/log /var/log/bahmni-two-factor-auth
    fi
}

bahmni-two-factor-auth_pid() {
        echo `ps -fe | grep 'bahmni-two-factor-auth.jar' | grep -v grep | tr -s " "|cut -d" " -f2`
}

start(){
    pid=$(bahmni-two-factor-auth_pid)
    if [ -n "$pid" ]
    then
        echo -e "\e[00;31mService bahmni-two-factor-auth is already running (pid: $pid)\e[00m"
    else
        # Start bahmni-two-factor-auth
        create_dirs
        echo -e "\e[00;32mStarting bahmni-two-factor-auth\e[00m"
        if [ `user_exists $BAHMNI_TWO_FACTOR_AUTH_USER` = "1" ]  && [ "$CUR_USER" != "$BAHMNI_TWO_FACTOR_AUTH_USER" ] ;
        then
                su -s /bin/bash $BAHMNI_TWO_FACTOR_AUTH_USER $BAHMNI_TWO_FACTOR_AUTH_RUN
        else
                sh $BAHMNI_TWO_FACTOR_AUTH_RUN
        fi
  fi
  return 0
}

debug(){
    pid=$(bahmni-two-factor-auth_pid)
    if [ -n "$pid" ]
    then
        echo -e "\e[00;31mService bahmni-two-factor-auth is already running (pid: $pid)\e[00m"
    else
        # Start bahmni-two-factor-auth
        create_dirs
        echo -e "\e[00;32mStarting bahmni-two-factor-auth\e[00m"
        if [ `user_exists $BAHMNI_TWO_FACTOR_AUTH_USER` = "1" ]  && [ "$CUR_USER" != "$BAHMNI_TWO_FACTOR_AUTH_USER" ] ;
        then
                /bin/su $BAHMNI_TWO_FACTOR_AUTH_USER -c $BAHMNI_TWO_FACTOR_AUTH_DEBUG
        else
                sh $BAHMNI_TWO_FACTOR_AUTH_DEBUG
        fi
  fi
  return 0
}

status(){
          pid=$(bahmni-two-factor-auth_pid)
          if [ -n "$pid" ]; then echo -e "\e[00;32mService bahmni-two-factor-auth is running with pid: $pid\e[00m"
          else echo -e "\e[00;31mService bahmni-two-factor-auth is not running\e[00m"
          fi
}

stop() {
	echo -e "\e[00;31mTerminating bahmni-two-factor-auth\e[00m"
	kill -9 $(bahmni-two-factor-auth_pid)
}
user_exists(){
        if id -u $1 >/dev/null 2>&1; then
        echo "1"
        else
                echo "0"
        fi
}

case $1 in
	start)
	  start
	;;
    debug)
	  debug
	;;
	stop)
	  stop
	;;
	restart)
	  stop
	  start
	;;
	status)
		status
	;;
	kill)
		stop
	;;
	*)

	;;
esac
exit 0
